# sudo systemctl start docker
# docker exec -it elasticsearch bin/elasticsearch-reset-password -u kibana_system -i pF*vitEA0z*xZ-ENF91a

services:
  Gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ticketeira_db;Username=postgres;Password=pF*vitEA0z*xZ-ENF91a
    depends_on:
      - EventService
      - SearchService
    networks:
      - rede-interna

  EventService:
    image: ${DOCKER_REGISTRY-}eventservice
    build:
      context: .
      dockerfile: EventService/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ticketeira_db;Username=postgres;Password=pF*vitEA0z*xZ-ENF91a
    depends_on:
      - postgres
      - redis
    networks:
      - rede-interna
  
  SearchService:
    image: ${DOCKER_REGISTRY-}searchservice
    build:
      context: .
      dockerfile: SearchService/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ticketeira_db;Username=postgres;Password=pF*vitEA0z*xZ-ENF91a
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      - rede-interna

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ticketeira_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pF*vitEA0z*xZ-ENF91a
    command: postgres -c wal_level=logical
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rede-interna

  redis:
    image: redis:alpine
    container_name: redis_cache

    volumes:
      - redisdata:/data
    networks:
      - rede-interna
    ports:
      - "6379:6379"
    restart: "no"
    command: ["redis-server", "--appendonly", "yes"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-elasticsearch-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=pF*vitEA0z*xZ-ENF91a
      - KIBANA_PASSWORD=pF*vitEA0z*xZ-ENF91a
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true         
      - xpack.security.http.ssl.enabled=false 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - rede-interna

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=pF*vitEA0z*xZ-ENF91a
    depends_on:
      - elasticsearch
    networks:
      - rede-interna

  zookeeper:
    image: quay.io/debezium/zookeeper:3.1
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - rede-interna

  kafka:
    image: quay.io/debezium/kafka:3.1
    container_name: kafka_debezium
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
    depends_on:
      - zookeeper
    networks:
      - rede-interna

  connect:
    image: quay.io/debezium/connect:3.1
    container_name: connect
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=connect_configs
      - OFFSET_STORAGE_TOPIC=connect_offsets
      - STATUS_STORAGE_TOPIC=connect_statuses
      - CONFIG_STORAGE_REPLICATION_FACTOR=1
      - OFFSET_STORAGE_REPLICATION_FACTOR=1
      - STATUS_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_PLUGIN_PATH=/usr/share/java,/kafka/connect,/data/connect-plugins
    volumes:
      - ./connect-plugins:/data/connect-plugins  
    depends_on:
      - kafka
      - postgres
    networks:
      - rede-interna

  connectors-init:
    image: curlimages/curl:latest
    container_name: connectors-init
    depends_on:
      - connect      
      - elasticsearch 
      - postgres
    volumes:
      - ./init.sh:/scripts/init.sh
    entrypoint: ["/bin/sh", "/scripts/init.sh"]
    networks:
      - rede-interna
      
volumes:
  pgdata:
  redisdata:
  es_data:
  
networks:
  rede-interna:
    driver: bridge