services:
  Gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ticketeira_db;Username=postgres;Password=sua_senha
    depends_on:
      - EventService
      - SearchService
    networks:
      - rede-interna

  EventService:
    image: ${DOCKER_REGISTRY-}eventservice
    build:
      context: .
      dockerfile: EventService/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ticketeira_db;Username=postgres;Password=sua_senha
    depends_on:
      - postgres
      - redis
    networks:
      - rede-interna
  
  SearchService:
    image: ${DOCKER_REGISTRY-}searchservice
    build:
      context: .
      dockerfile: SearchService/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ticketeira_db;Username=postgres;Password=sua_senha
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      - rede-interna

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ticketeira_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rede-interna

  redis:
    image: redis:alpine
    container_name: redis_cache

    volumes:
      - redisdata:/data
    networks:
      - rede-interna
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--appendonly", "yes"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-elasticsearch-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme123
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - rede-interna

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme123
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    depends_on:
      - elasticsearch
    networks:
      - rede-interna

  zookeeper:
    image: quay.io/debezium/zookeeper:3.1
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - rede-interna

  kafka:
    image: quay.io/debezium/kafka:3.1
    container_name: kafka_debezium
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
    depends_on:
      - zookeeper
    networks:
      - rede-interna

  connect:
    image: quay.io/debezium/connect:3.1
    container_name: connect
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=connect_configs
      - OFFSET_STORAGE_TOPIC=connect_offsets
      - STATUS_STORAGE_TOPIC=connect_statuses
      - CONFIG_STORAGE_REPLICATION_FACTOR=1
      - OFFSET_STORAGE_REPLICATION_FACTOR=1
      - STATUS_STORAGE_REPLICATION_FACTOR=1
    depends_on:
      - kafka
      - postgres
    networks:
      - rede-interna

volumes:
  pgdata:
  redisdata:
  esdata:
  
networks:
  rede-interna:
    driver: bridge